---
Python functions
---

mindmap
    root(Python functions)
        term)Definition(
        def[Function definition syntax]
            example
        scope{{Variables scopes}}
        ::[Arguments]
            positional arguments
            keyword arguments
            ::{{Special cases}}
                default values
                ::[Variable number of arguments]
                    pos(Positional arguments)
                    kw(Keyword arguments)
        m_args{{Mutable arguments}}
            ::{{special case: default values}}
        return[return statement]
        lambda(Lambda functions)
