---
Introduction to Django web framework
---

mindmap
    root(Django Introduction)
        about)About(
            Frameworks
            Libraries
        hiw))How<br>internet<br>works((
            diagram[Request-Response cycle<br>diagram]
            response)What is<br>RESPONSE?(
            request)What is<br>REQUEST?(
                methods{{Request methods}}
        mvc(Model,&nbsp;View,&nbsp;Controller<br>design pattern)
            mvc_m[Model]
                ::{{Data manipulation}}
            mvc_v[View]
                ::{{Data representation}}
            mvc_c[Controller]
                ::{{Model-to-view mapper}}
        mvt(Model,&nbsp;View,&nbsp;Template<br>design pattern)
            dj_m[Model]
                ::{{Data manipulation}}
            dj_v[View]
                ::{{Request-response handlers}}
            dj_t[Template]
                ::{{Data representation}}
        how_to)How to(
            Install Django
            Create project
            Run project for the first time
        structure[Django project structure]
            ::{{Entry points}}
            ::{{Settings}}
            ::{{URL Configurations}}
            apps[Django applications]
                Create app
                ::{{AppConfig}}
                Install app
