---
Django templates
---

mindmap
    root(Django templates)
        settings
        ::icon(fas fa-gear)
            ::[Template directories]
            ::icon(fas fa-folder)
            ::{{Apps templates}}
        render(render function)
            ctx[context]
        dtl)Django<br>template<br>language(
            syntax((Syntax))
                tags
                variables
                filters
                comments
            ::(access data)
            ::(conditions)
            ::(loops)
            ::(include)
            ::(templates<br>inheritance)
            ctg{{Custom template tags}}
                templatetags
