---
ACID - Atomicity, Consistency, Isolation, Durability
---

mindmap
    root((ACID))
        term)transactions(
        A(Atomicity)
            Individual operations
            ::[All or nothing]
        C(Consistency)
            ::{{valid state}}
            From valid state to another valid state
        I(Isolation)
            Isolation principle
            levels[Isolation levels]
        D(Durability)
